### ISSUE TITLE
Thank you for this interesting code!

### ISSUE THREAD

**Issue by clort81** [bathtaters/wavbuild#7]
Cool 'first c program'!  Proper low-level bitwise operations.  Easy for me to understand.

Compiling on aarch64 linux, with gcc-12, i had to add #include <stdint.h> to timecode.h and mkdir out before running 'make'.

I am also curious what all the effort to implement timecodes, pulldown was for. All I've dealt with before was format, samplerate, channels...  

If i have one complaint, it's the difficulty of getting image of soggy taters floating in a bathtub out of my brain.  

Thanks for sharing!

**Comment by bathtaters** [comment]
Awesome, glad someone found this! And thank you for catching that, hopefully this fixed it!

**Comment by bathtaters** [comment]
Oh also to answer your question, I was mainly creating this to generate LTC for simple music video playback, since all of that affects the actual LTC audio signal. I forget if I ever got it to work since https://elteesee.pehrhovey.net/ came about and I abandoned it.
